### ISSUE TITLE
Breaking change in deepMerge function signature in v0.92.11

### ISSUE THREAD

**Issue by rubenfonseca** [projen/projen#4261]
## Summary

The `deepMerge` function from `projen/lib/util` had a breaking API change in version 0.92.11 that breaks existing code.

## Breaking Change Details

**Commit:** 955da1bc152dc0d879c7a70d9571ae7bd3b0fcdb
**Affected Function:** `deepMerge` in `src/util.ts`

**Old Signature (v0.92.9):**
```typescript
export function deepMerge(
  objects: Array<Obj<any> | undefined>,
  destructive: boolean = false
)
```

**New Signature (v0.92.11):**
```typescript
export function deepMerge(
  objects: Array<Obj<any> | undefined>,
  { destructive = false, mergeArrays = false }: MergeOptions = {}
)
```

## Problem

This change breaks existing code that calls `deepMerge` with a boolean as the second parameter:

```typescript
// This worked in v0.92.9
deepMerge(objects, true)

// This fails in v0.92.11 with TypeScript error:
// TS2559: Type 'boolean' has no properties in common with type 'MergeOptions'
```

## Impact

- Any consumer of `projen/lib/util` using `deepMerge` will break upon upgrading
- Forces downstream users to update their code when upgrading projen patch versions
- Breaks builds that depend on the existing API

## Reproduction

1. Upgrade projen from 0.92.9 to 0.92.11
2. Call `deepMerge(objects, boolean)` in TypeScript code
3. Observe TypeScript compilation error

## Example Error

```
TSError: ⨯ Unable to compile TypeScript:
error TS2559: Type 'boolean' has no properties in common with type 'MergeOptions'.
```

This issue affects any project that imports and uses the `deepMerge` utility function from projen with the previous calling convention.

**Comment by mrgrain** [comment]
Ah yes, sorry. We should have released this as `0.93.0`.
