### ISSUE TITLE
awscdk: Property 'marker' does not exist on type 'typeof FileBase'.

### ISSUE THREAD

**Issue by dannysteenman** [projen/projen#1615]
In v0.52.0 `FileBase.PROJEN_MARKER` was deprecated and changed in favor of `FileBase.marker`: https://github.com/projen/projen/pull/1459

However when I updated from projen 0.50.17 to 0.52.4 and change the following:

```
new TextFile(project, '.husky/pre-push', {
  executable: true,
  lines: [
    `#${FileBase.PROJEN_MARKER}`,
    'git diff HEAD --quiet',
    'npx projen test',
  ],
});
```

to 
```
new TextFile(project, '.husky/pre-push', {
  executable: true,
  lines: [
    `#${FileBase.marker}`,
    'git diff HEAD --quiet',
    'npx projen test',
  ],
});
```

I get the error: `Property 'marker' does not exist on type 'typeof FileBase'.`

**Comment by mmcculloh-dms** [comment]
`marker` is an instance property now rather than static. [Example of new usage](https://github.com/projen/projen/blob/main/src/gitattributes.ts#L44) 

In order to use it, you'd have to create a new component that extends `FileBase` (or `TextFile` in your case) and then you can access it via `this.marker`. 
It's a public property, so you can also technically grab it off of any FileBase instance
