### ISSUE TITLE
Task runner regression in 0.101.0: `$(...)` command substitution throws 'Not implemented: command'

### ISSUE THREAD

**Issue by sma-nextdoor** [projen/projen#4783]
## Summary

projen `0.101.0` introduced a cross-platform shell ([#4770](https://github.com/projen/projen/pull/4770), commit [8a24b61](https://github.com/projen/projen/commit/8a24b612659928777925fac1a229c26bd3cdd642)) that **does not implement `$(...)` command substitution**. Any task `exec` step that uses `$(...)` — either in argument position or in a variable assignment — throws `Not implemented: command` and aborts.

This is a regression — the [0.101.0 release notes](https://github.com/projen/projen/releases/tag/v0.101.0) explicitly call out `$(...)` as a feature that flows through the new shell:

> Tasks, conditions and **dynamic (`$(...)`) environment variables** now run through projen's built-in cross-platform shell on **all** platforms.

…so the intent was clearly to support `$(...)`, not to break it.

## Reproduction

Minimal repro — one task file, one line:

```bash
mkdir repro && cd repro
cat > package.json <<'PKG'
{ "name": "repro", "version": "0.0.1", "private": true, "devDependencies": { "projen": "0.101.1" } }
PKG
mkdir .projen
cat > .projen/tasks.json <<'TASKS'
{ "tasks": { "t": { "name": "t", "steps": [ { "exec": "X=$(echo hi); echo $X" } ] } } }
TASKS
npm install --silent
npx projen t
```

**Expected** (works in 0.100.7):
```
👾 t | X=$(echo hi); echo $X
hi
```

**Actual** (in 0.101.0 and 0.101.1):
```
👾 t | X=$(echo hi); echo $X
👾 Not implemented: command
```

## Affected patterns (all fail on 0.101.x)

| Pattern | Note |
|---|---|
| `X=$(echo hi)` | Command substitution in assignment |
| `echo $(echo wrapped)` | Command substitution in argument position |
| `X=$(echo hi); echo $X` | Combined assignment + use |

For comparison, **these work fine** on both 0.100.7 and 0.101.x:
- `echo a; echo b` (sequential `;`)
- `X=hi; echo $X` (bare assignment + use)
- `echo $X` (variable expansion alone)

So the issue is **specifically** `$(...)` — every other primitive in this set works.

## Impact

We hit this on a CodeArtifact authentication task that's a very common projen-ecosystem pattern:

```
npm config set @scope:registry https://...;
CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain ... --query authorizationToken --output text);
npm config set //...:_authToken=$CODEARTIFACT_AUTH_TOKEN
```

The pattern of "shell out to a CLI, capture the output into an env var, use the env var on a subsequent line" is extremely common. We have 4 production repos that hit this within hours of 0.101.0 being released; pinning to `~0.100` as a workaround.

## Environment

- projen 0.101.1 (also reproed on 0.101.0)
- Node 22, macOS, Linux (GitHub Actions runners)
- node-package.js / standard NodeProject task layout

## Suggested triage

Either the cross-platform shell needs `$(...)` support implemented, or it needs to fall back to the system shell for tasks containing `$(...)`. Happy to test a patch.

Thanks for the project!

**Comment by sma-nextdoor** [comment]
Closing this myself with an apology — I misread the 0.101.0 release notes when filing.

Re-reading carefully, the release notes call this out as a **deliberate breaking change** rather than a regression:

> Any tasks relying on system- or bash-specific behavior may need to opt back in. To restore the previous behavior, run the task through the system shell: set `project.tasks.shell = TaskShell.system()` for the whole project, or pass `{ shell: TaskShell.system() }` to an individual task or `exec` step.

I incorrectly read "dynamic (`$(...)`) environment variables now run through projen's built-in cross-platform shell" as a claim that bash `$(...)` was newly supported in task strings, when in context it was actually a noun phrase describing projen's own env-var-substitution feature. My mistake.

For anyone landing here with the same `Not implemented: command` error: the projen-blessed workaround is `project.tasks.shell = TaskShell.system()` (project-wide) or `{ shell: TaskShell.system() }` (per-task / per-step). Confirmed working on 0.101.1.

One small UX nit, not worth a separate issue but mentioning in case it's useful: the runtime error `Not implemented: command` is opaque about both the cause (bash-only syntax) and the fix (`TaskShell.system()`). A pointer to the migration guidance in the error message would have saved me an investigation cycle. Closing this issue since the behavior itself is intentional and documented.

Thanks for the project!

**Comment by mrgrain** [comment]
All good and sorry this broke your app. I've update the changelog slightly. Hopefully that makes it clearer. Otherwise good suggestion re the error message.

**Comment by mrgrain** [comment]
Either way, should be fixed soon: https://github.com/dsherret/dax/pull/402#issuecomment-4837505165

also looking at error message improvements
